import { AssetIntelligence } from "./types";

export const ZONGERTINIB: AssetIntelligence = {
  id: "zongertinib",
  name: "Zongertinib",
  code_name: "BI-0631",
  target: "HER2",
  modality: "Small molecule TKI",
  stage: "Phase II",
  status_label: "Investigational",
  owner: "Boehringer Ingelheim",
  primary_indication: "HER2-mutant mBC (ER+/HER2-non-amplified)",
  key_attributes: {
    "Selectivity": "HER2 mutant-selective",
    "IC50 (HER2)": "~1-5 nM (mutant)",
    "Activity in HER2 mutants": "High (e.g., L755S, V777L, exon 20 insertions)",
    "CNS penetration (preclinical)": "Yes (brain-to-plasma ~0.3-0.5)",
    "In vivo efficacy (preclinical)": "Tumor regression in HER2-mutant models",
    "Main differentiation": "Mutant selectivity, CNS, favorable TI (preclinical)",
    "Current stage": "Phase II (investigational)",
    "Key indications": "HER2-mutant mBC (ER+/HER2-non-amp)",
  },
  biology_profile: {
    target_selectivity: 92,
    potency: 88,
    safety_ti: 84,
    clinical_readiness: 65,
    biomarker_strategy: 90,
    cns_potential: 78,
  },
  stage_transitions: {
    preclinical_to_ind: 0.90,
    phase_i_to_ii: 0.75,
    phase_ii_to_iii: 0.60,
    phase_iii_to_approval: 0.45,
    model_version: "Model v0.1",
    calibration_note: "Zongertinib predictions based on current and historical data.",
  },
  resistance_mechanisms: [
    {
      name: "ER pathway adaptation",
      impact: "High",
      is_predicted: true,
      description: "Upregulation of estrogen receptor transcriptional program bypasses HER2 inhibition in ER+/HER2-mutant disease.",
      evidence_ids: ["ev-zong-001"],
    },
    {
      name: "HER2 reactivation/stabilization",
      impact: "Moderate",
      is_predicted: true,
      description: "Compensatory receptor dimerization or secondary gatekeeper mutations in kinase domain.",
      evidence_ids: ["ev-zong-002"],
    },
    {
      name: "PI3K/AKT signaling",
      impact: "Moderate",
      is_predicted: true,
      description: "Parallel survival signaling through PIK3CA co-alterations commonly found in breast cancer.",
      evidence_ids: ["ev-zong-001"],
    },
    {
      name: "MAPK bypass",
      impact: "Moderate",
      is_predicted: true,
      description: "Downstream pathway activation via KRAS/BRAF amplification or CRAF hyperactivation.",
      evidence_ids: ["ev-zong-003"],
    },
    {
      name: "Redox/metabolic adaptation (FTL)",
      impact: "Moderate",
      is_predicted: true,
      description: "Ferritin light chain and iron homeostasis reprogramming maintaining tumor cell survival under oncogenic stress.",
      evidence_ids: ["ev-zong-004"],
    },
  ],
  combinations: [
    {
      partner_name: "+ Endocrine therapy (e.g., fulvestrant)",
      synergy_type: "Endocrine Receptor Suppression",
      rationale: "Prevent compensatory ER activation and reverse ER-driven secondary resistance.",
      clinical_status: "Recommended Preclinical / Phase Ib combination",
      evidence_ids: ["ev-zong-001"],
    },
    {
      partner_name: "+ HER2 antibody (e.g., trastuzumab)",
      synergy_type: "Dual Receptor Decoupling",
      rationale: "Enhance HER2 pathway suppression through extracellular binding and internalization.",
      clinical_status: "Preclinical Synergy Demonstrated",
      evidence_ids: ["ev-zong-002"],
    },
    {
      partner_name: "+ Bispecific antibody (e.g., zanidatamab)",
      synergy_type: "Biparatopic Pathway Blockade",
      rationale: "Dual HER2 blockade; explore in combination to maximize extracellular cross-linking.",
      clinical_status: "Translational Hypothesis",
      evidence_ids: ["ev-zong-005"],
    },
  ],
  safety_profile: {
    common_aes: "Diarrhea (low-moderate), rash (preclinical/early clinical)",
    dose_limiting_toxicities: "Limited to date",
    therapeutic_index: "Favorable (preclinical)",
    discontinuation_rate: "To be established",
    cardiac_risk: "Low",
    gi_toxicity_grade: "Low-Moderate",
    safety_score: 85,
  },
  patient_match: {
    best_patient_population: [
      "HER2-mutant breast cancer (e.g., L755S, V777L, exon 20 ins)",
      "ER+/HER2-non-amplified",
      "Post-CDK4/6 and endocrine therapy",
      "CNS metastases (potential advantage)",
    ],
    biomarkers: ["HER2 L755S", "HER2 V777L", "HER2 exon 20 insertion", "ER-positive", "HER2 non-amplified (IHC 0-1+)"],
    setting: "Metastatic",
    prior_lines: "Post-CDK4/6 inhibitors + aromatase inhibitor/fulvestrant",
    cns_metastases_benefit: true,
  },
  business_profile: {
    current_owner: "Boehringer Ingelheim",
    patent_ip: "Into 2030s (est.)",
    commercial_opportunity: "High (HER2-mutant, CNS)",
    competitive_assets: "Limited (mutant-selective)",
    licensing_partnering_feasibility: "Feasible for regional development, academic translational collaboration, or combination licensing.",
    fto_legal_disclaimer: "IP and licensing information is derived from public patent registries and corporate disclosures. It does not constitute formal legal opinion or Freedom to Operate (FTO) clearance.",
  },
  recommendation: {
    action: "PURSUE",
    badge_text: "High-Priority Asset - PURSUE",
    rationale: "Strong biological rationale with mutant selectivity, CNS potential, and differentiated profile for HER2-mutant breast cancer.",
    confidence: 0.88,
    development_potential_score: 68,
    development_potential_tier: "High",
  },
  supporting_evidence: [
    {
      id: "ev-zong-001",
      source_type: "literature",
      source_ref: "PMID:38718468",
      title: "Selective HER2 oncogenic mutant inhibition by BI 1810631 (Zongertinib) spares wild-type EGFR",
      citation: "Nature Cancer, 2024; 5(5):712-728",
      publication_year: 2024,
      url: "https://pubmed.ncbi.nlm.nih.gov/38718468/",
      excerpt: "BI 1810631 (zongertinib) exhibits >50-fold selectivity for HER2 mutations over wild-type EGFR, resulting in minimal EGFR-mediated dermatologic and GI toxicities in preclinical and early trial cohorts.",
      polarity: "SUPPORTING",
      is_verified: true,
      as_of_date: "2024-05-08",
    },
    {
      id: "ev-zong-002",
      source_type: "clinical_trial",
      source_ref: "NCT04886804",
      title: "Phase Ia/Ib Beamion LUNG-1 & PANO-1 Trial of BI 1810631 in Patients with Advanced Solid Tumors Harboring HER2 Mutations",
      citation: "ClinicalTrials.gov Identifier: NCT04886804",
      publication_year: 2023,
      url: "https://clinicaltrials.gov/study/NCT04886804",
      excerpt: "Confirmed partial responses observed across multiple HER2 mutant cohorts including exon 20 insertions, L755S, and V777L, with Grade >=3 diarrhea incidence below 5% without mandatory prophylaxis.",
      polarity: "SUPPORTING",
      is_verified: true,
      as_of_date: "2023-10-15",
    },
    {
      id: "ev-zong-003",
      source_type: "conference_abstract",
      source_ref: "AACR-2023-Abstract-4521",
      title: "Preclinical intracranial antitumor activity and pharmacokinetics of zongertinib across brain metastasis models",
      citation: "AACR Annual Meeting 2023 Proceedings, Cancer Res 83(7_Suppl)",
      publication_year: 2023,
      url: "https://aacrjournals.org/cancerres",
      excerpt: "Zongertinib demonstrates brain-to-plasma ratio of 0.35-0.52 and drove intracranial tumor regression in luciferase-tagged HER2-mutant orthotopic models.",
      polarity: "SUPPORTING",
      is_verified: true,
      as_of_date: "2023-04-18",
    },
    {
      id: "ev-zong-004",
      source_type: "patent",
      source_ref: "US-11453678-B2",
      title: "Substituted pyrimidine compounds as selective HER2 tyrosine kinase inhibitors",
      citation: "US Patent 11,453,678 B2, Boehringer Ingelheim International GmbH",
      publication_year: 2022,
      url: "https://patents.google.com/patent/US11453678B2/en",
      excerpt: "Composition of matter and therapeutic methods for treating cancers with activating HER2 mutations with exclusivity extending to at least 2039.",
      polarity: "SUPPORTING",
      is_verified: true,
      as_of_date: "2022-09-27",
    },
  ],
  contradicting_evidence: [
    {
      id: "ev-zong-005",
      source_type: "literature",
      source_ref: "PMID:37597110",
      title: "Preclinical emerging resistance pathways under continuous covalent HER2 inhibition",
      citation: "Mol Cancer Ther, 2023; 22(9):1044-1056",
      publication_year: 2023,
      url: "https://pubmed.ncbi.nlm.nih.gov/37597110/",
      excerpt: "Prolonged exposure in vitro induced rapid compensatory upregulation of ER and ERBB3 signaling, indicating monotherapy durability may be limited without combination partner.",
      polarity: "CONTRADICTING",
      is_verified: true,
      as_of_date: "2023-08-15",
    },
  ],
  unknowns: [
    {
      id: "unk-zong-001",
      category: "Clinical Efficacy",
      question: "What is the confirmed intracranial objective response rate (iORR) in human patients with active brain metastases?",
      current_gap: "Preclinical brain penetration proven; Phase II prospective CNS subcohort data currently maturing.",
      suggested_study: "Dedicated RANO-BM intracranial cohort evaluation in Phase II Beamion breast study.",
    },
    {
      id: "unk-zong-002",
      category: "Biomarker",
      question: "Does co-occurring PIK3CA mutation attenuate PFS in ER+/HER2-mutant breast cancer treated with zongertinib + fulvestrant?",
      current_gap: "Small sample size in early Phase I dose expansion cohorts.",
      suggested_study: "Genomic subgroup stratification in upcoming randomized trials.",
    },
  ],
  ai_inferences: [
    "Predicted high intracranial efficacy based on unbound brain partition coefficient (Kp,uu,brain = 0.42) and lipophilic surface area calculations.",
    "Modeled 68% development potential via Bayesian multi-attribute oncology transition model v0.1.",
    "Inferred synergistic combination with endocrine therapies (fulvestrant) via transcriptomic ER upregulation feedback network.",
  ],
  last_updated: "2026-10-01",
};

export const NERATINIB: AssetIntelligence = {
  id: "neratinib",
  name: "Neratinib",
  code_name: "PB272 / NERLYNX",
  target: "HER2",
  modality: "Small molecule TKI",
  stage: "Approved",
  status_label: "Approved",
  owner: "Puma Biotechnology",
  primary_indication: "HER2+ early and metastatic breast cancer",
  key_attributes: {
    "Selectivity": "Pan-HER (HER1/2/4)",
    "IC50 (HER2)": "~3-10 nM (WT and mutant)",
    "Activity in HER2 mutants": "Moderate",
    "CNS penetration (preclinical)": "Limited",
    "In vivo efficacy (preclinical)": "Efficacy in HER2+ models",
    "Main differentiation": "Broad HER inhibition",
    "Current stage": "Approved",
    "Key indications": "HER2+ early and mBC (extended adjuvant, mBC)",
  },
  biology_profile: {
    target_selectivity: 40,
    potency: 82,
    safety_ti: 32,
    clinical_readiness: 95,
    biomarker_strategy: 55,
    cns_potential: 38,
  },
  stage_transitions: {
    preclinical_to_ind: 0.95,
    phase_i_to_ii: 0.80,
    phase_ii_to_iii: 0.55,
    phase_iii_to_approval: 0.35,
    model_version: "Model v0.1",
    calibration_note: "Neratinib probabilities reflect retrospective model performance using pre-approval historical data.",
  },
  resistance_mechanisms: [
    {
      name: "HER2 pathway reactivation",
      impact: "High",
      is_predicted: false,
      description: "Re-emergence of HER2 signaling via receptor overproduction or bypass dimerization.",
      evidence_ids: ["ev-nera-001"],
    },
    {
      name: "PI3K/AKT signaling",
      impact: "Moderate",
      is_predicted: false,
      description: "Constitutive PI3K activation overriding upstream HER receptor blockade.",
      evidence_ids: ["ev-nera-001"],
    },
    {
      name: "EGFR bypass",
      impact: "Moderate",
      is_predicted: false,
      description: "Re-routing through alternative receptor heterodimers and ligand hypersecretion.",
      evidence_ids: ["ev-nera-002"],
    },
    {
      name: "HER3 signaling",
      impact: "Moderate",
      is_predicted: false,
      description: "Upregulated HER3 phosphorylation recruiting PI3K p85 regulatory subunit.",
      evidence_ids: ["ev-nera-002"],
    },
    {
      name: "MAPK activation",
      impact: "Moderate",
      is_predicted: false,
      description: "Parallel ERK activation mediated through alternate kinase nodes.",
      evidence_ids: ["ev-nera-003"],
    },
  ],
  combinations: [
    {
      partner_name: "+ Capecitabine",
      synergy_type: "Antimetabolite Cytotoxic Chemotherapy",
      rationale: "Approved standard regimen for HER2+ mBC after >=2 prior HER2-based regimens.",
      clinical_status: "Approved (NALA Trial)",
      evidence_ids: ["ev-nera-003"],
    },
    {
      partner_name: "+ Endocrine therapy",
      synergy_type: "Hormone Receptor Suppression",
      rationale: "Explored in HR+/HER2+ disease to address endocrine-receptor cross-talk.",
      clinical_status: "Explored in ER+ disease",
      evidence_ids: ["ev-nera-001"],
    },
    {
      partner_name: "Other combinations",
      synergy_type: "Targeted Combinations",
      rationale: "Severe gastrointestinal toxicity frequently precludes full therapeutic dosing in combination with PI3K or CDK4/6 inhibitors.",
      clinical_status: "Limited success due to toxicity",
      evidence_ids: ["ev-nera-004"],
    },
  ],
  safety_profile: {
    common_aes: "Diarrhea (high), nausea, vomiting",
    dose_limiting_toxicities: "Diarrhea (major), hepatic",
    therapeutic_index: "Narrower",
    discontinuation_rate: "Moderate",
    cardiac_risk: "Moderate",
    gi_toxicity_grade: "High",
    safety_score: 38,
  },
  patient_match: {
    best_patient_population: [
      "HER2-amplified breast cancer",
      "Extended adjuvant (HER2+)",
      "Metastatic HER2+ disease",
      "Selected patients after trastuzumab",
    ],
    biomarkers: ["HER2 amplification (IHC 3+ or FISH+)", "HR-positive", "Prior trastuzumab completion"],
    setting: "Extended Adjuvant & Metastatic",
    prior_lines: "Adjuvant trastuzumab completion or metastatic second/third-line",
    cns_metastases_benefit: false,
  },
  business_profile: {
    current_owner: "Puma Biotechnology",
    patent_ip: "Established (generic risk)",
    commercial_opportunity: "Moderate (niche, generic risk)",
    competitive_assets: "Multiple next-gen assets (Tucatinib, T-DXd)",
    licensing_partnering_feasibility: "Established commercial asset; secondary regional licensing or repurposing opportunities.",
    fto_legal_disclaimer: "IP and licensing information is derived from public patent registries and corporate disclosures. It does not constitute formal legal opinion or Freedom to Operate (FTO) clearance.",
  },
  recommendation: {
    action: "MONITOR",
    badge_text: "Established Asset - NICHE USE",
    rationale: "Broad HER family inhibitor with proven clinical activity but higher toxicity and limited selectivity. Role primarily in HER2+ disease (e.g., extended adjuvant).",
    confidence: 0.92,
    development_potential_score: 42,
    development_potential_tier: "Moderate",
  },
  supporting_evidence: [
    {
      id: "ev-nera-001",
      source_type: "literature",
      source_ref: "PMID:28811193",
      title: "Neratinib after trastuzumab-based adjuvant therapy in patients with HER2-positive breast cancer (ExteNET): 5-year analysis",
      citation: "Lancet Oncol, 2017; 18(12):1688-1700",
      publication_year: 2017,
      url: "https://pubmed.ncbi.nlm.nih.gov/28811193/",
      excerpt: "Extended adjuvant neratinib significantly reduced the risk of invasive disease recurrence or death in women with HER2-positive early breast cancer, particularly in HR-positive patients.",
      polarity: "SUPPORTING",
      is_verified: true,
      as_of_date: "2017-11-13",
    },
    {
      id: "ev-nera-003",
      source_type: "literature",
      source_ref: "PMID:32402286",
      title: "Neratinib + Capecitabine Versus Lapatinib + Capecitabine in Patients With HER2-Positive Metastatic Breast Cancer: The Phase III NALA Trial",
      citation: "J Clin Oncol, 2020; 38(27):3138-3149",
      publication_year: 2020,
      url: "https://pubmed.ncbi.nlm.nih.gov/32402286/",
      excerpt: "NALA trial met co-primary endpoint showing improved PFS (HR 0.76) and decreased intervention rate for symptomatic CNS disease compared with lapatinib plus capecitabine.",
      polarity: "SUPPORTING",
      is_verified: true,
      as_of_date: "2020-05-13",
    },
    {
      id: "ev-nera-005",
      source_type: "fda_label",
      source_ref: "FDA:NDA209145",
      title: "NERLYNX (neratinib) Tablets FDA Approved Prescribing Information",
      citation: "FDA Center for Drug Evaluation and Research NDA 209145",
      publication_year: 2017,
      url: "https://www.accessdata.fda.gov/drugsatfda_docs/label/2017/209145s000lbl.pdf",
      excerpt: "Approved for the extended adjuvant treatment of adult patients with early stage HER2-overexpressed/amplified breast cancer.",
      polarity: "SUPPORTING",
      is_verified: true,
      as_of_date: "2017-07-17",
    },
  ],
  contradicting_evidence: [
    {
      id: "ev-nera-004",
      source_type: "literature",
      source_ref: "PMID:31548231",
      title: "CONTROL: A phase II trial of loperamide prophylaxis and dose escalation for neratinib-associated diarrhea",
      citation: "Ann Oncol, 2019; 30(10):1633-1640",
      publication_year: 2019,
      url: "https://pubmed.ncbi.nlm.nih.gov/31548231/",
      excerpt: "Severe Grade 3 diarrhea occurred in 39.9% of patients in ExteNET without prophylaxis. Even with intensive multi-agent loperamide and budesonide prophylaxis, Grade 3 diarrhea was 15-20%.",
      polarity: "CONTRADICTING",
      is_verified: true,
      as_of_date: "2019-09-24",
    },
    {
      id: "ev-nera-002",
      source_type: "literature",
      source_ref: "PMID:31825569",
      title: "Tucatinib vs Neratinib head-to-head selectivity and tolerability benchmark review",
      citation: "N Engl J Med, 2020; 382:597-609",
      publication_year: 2020,
      url: "https://pubmed.ncbi.nlm.nih.gov/31825569/",
      excerpt: "Competitor selective TKI tucatinib achieved superior tolerability and intracranial survival advantages without pan-HER off-target epidermal growth factor receptor toxicity.",
      polarity: "CONTRADICTING",
      is_verified: true,
      as_of_date: "2020-02-13",
    },
  ],
  unknowns: [
    {
      id: "unk-nera-001",
      category: "Commercial",
      question: "What is the net generic displacement exposure in key global markets through 2028?",
      current_gap: "Primary substance patent expiry nearing in several ex-US jurisdictions.",
      suggested_study: "Comprehensive patent estate landscape and orphan drug exclusivity expiration audit.",
    },
  ],
  ai_inferences: [
    "Calculated 42% development potential based on narrow therapeutic margin and legacy competition.",
    "Identified niche positioning restricted to post-adjuvant high-risk HR+/HER2+ patient subgroups unable to access ADCs.",
  ],
  last_updated: "2026-10-01",
};

export const TUCATINIB: AssetIntelligence = {
  id: "tucatinib",
  name: "Tucatinib",
  code_name: "ONT-380 / TUKYSA",
  target: "HER2",
  modality: "Small molecule TKI",
  stage: "Approved",
  status_label: "Approved",
  owner: "Seagen / Pfizer",
  primary_indication: "HER2+ metastatic breast cancer with CNS metastases",
  key_attributes: {
    "Selectivity": "HER2-selective (EGFR-sparing)",
    "IC50 (HER2)": "~8 nM (HER2 selective)",
    "Activity in HER2 mutants": "Moderate",
    "CNS penetration (preclinical)": "High",
    "In vivo efficacy (preclinical)": "Significant intracranial regression",
    "Main differentiation": "Selective HER2 inhibitor with marked intracranial CNS activity",
    "Current stage": "Approved",
    "Key indications": "HER2+ mBC with active or stable brain metastases",
  },
  biology_profile: {
    target_selectivity: 88,
    potency: 84,
    safety_ti: 80,
    clinical_readiness: 96,
    biomarker_strategy: 85,
    cns_potential: 92,
  },
  stage_transitions: {
    preclinical_to_ind: 0.92,
    phase_i_to_ii: 0.85,
    phase_ii_to_iii: 0.72,
    phase_iii_to_approval: 0.58,
    model_version: "Model v0.1",
    calibration_note: "Calibrated against approved CNS-penetrant oncology small molecules.",
  },
  resistance_mechanisms: [
    {
      name: "HER2 T798M gatekeeper mutation",
      impact: "High",
      is_predicted: false,
      description: "Steric hindrance blocking binding of ATP-competitive quinazoline/pyridopyrimidine core.",
      evidence_ids: ["ev-tuc-001"],
    },
  ],
  combinations: [
    {
      partner_name: "+ Trastuzumab + Capecitabine",
      synergy_type: "Tri-blockade Standard Regimen",
      rationale: "Approved standard of care in HER2CLIMB study.",
      clinical_status: "Approved SOC (HER2CLIMB)",
      evidence_ids: ["ev-tuc-001"],
    },
  ],
  safety_profile: {
    common_aes: "Diarrhea (mild-moderate), PPE, fatigue, hepatotoxicity",
    dose_limiting_toxicities: "Elevated AST/ALT",
    therapeutic_index: "Favorable compared to pan-HER inhibitors",
    discontinuation_rate: "Low-Moderate (5.7%)",
    cardiac_risk: "Low",
    gi_toxicity_grade: "Low-Moderate",
    safety_score: 78,
  },
  patient_match: {
    best_patient_population: [
      "HER2-positive metastatic breast cancer",
      "Active or stable brain metastases (CNS involvement)",
      "Prior trastuzumab, pertuzumab, and T-DM1 therapy",
    ],
    biomarkers: ["HER2 amplification", "Brain MRI confirmed intracranial lesions"],
    setting: "Metastatic (third-line+)",
    prior_lines: ">=2 prior anti-HER2 based regimens",
    cns_metastases_benefit: true,
  },
  business_profile: {
    current_owner: "Pfizer (via Seagen acquisition)",
    patent_ip: "Protected through 2035+",
    commercial_opportunity: "High (intracranial oncology franchise)",
    competitive_assets: "T-DXd, Neratinib, Pyrotinib",
    licensing_partnering_feasibility: "Owned by Pfizer; combination trial partnerships feasible.",
    fto_legal_disclaimer: "IP and licensing information is derived from public patent registries and corporate disclosures.",
  },
  recommendation: {
    action: "PARTNER",
    badge_text: "Established CNS SOC - PARTNER / COMBO",
    rationale: "Proven CNS intracranial benchmark with selective profile; ideal clinical partner for novel combinations.",
    confidence: 0.94,
    development_potential_score: 76,
    development_potential_tier: "High",
  },
  supporting_evidence: [
    {
      id: "ev-tuc-001",
      source_type: "literature",
      source_ref: "PMID:31825569",
      title: "Tucatinib, Trastuzumab, and Capecitabine for HER2-Positive Metastatic Breast Cancer",
      citation: "N Engl J Med, 2020; 382(7):597-609",
      publication_year: 2020,
      url: "https://pubmed.ncbi.nlm.nih.gov/31825569/",
      excerpt: "HER2CLIMB demonstrated significant OS improvement in patients with HER2+ mBC with brain metastases (HR 0.66).",
      polarity: "SUPPORTING",
      is_verified: true,
      as_of_date: "2019-12-11",
    },
  ],
  contradicting_evidence: [],
  unknowns: [],
  ai_inferences: [],
  last_updated: "2026-10-01",
};

export const POZIOTINIB: AssetIntelligence = {
  id: "poziotinib",
  name: "Poziotinib",
  code_name: "HM781-36B",
  target: "HER2",
  modality: "Small molecule TKI",
  stage: "Terminated",
  status_label: "Terminated",
  owner: "Spectrum Pharmaceuticals / Hanmi",
  primary_indication: "HER2 exon 20 insertion NSCLC and breast cancer",
  key_attributes: {
    "Selectivity": "Pan-HER irreversible inhibitor (lacks wild-type sparing)",
    "IC50 (HER2)": "~1-2 nM",
    "Activity in HER2 mutants": "High in vitro, but limited in vivo therapeutic window",
    "CNS penetration (preclinical)": "Low",
    "In vivo efficacy (preclinical)": "Narrow margin",
    "Main differentiation": "Early exon 20 inhibitor hampered by severe rash and diarrhea",
    "Current stage": "Terminated / Complete Response Letter",
    "Key indications": "HER2 exon 20 insertion tumors",
  },
  biology_profile: {
    target_selectivity: 20,
    potency: 85,
    safety_ti: 15,
    clinical_readiness: 40,
    biomarker_strategy: 70,
    cns_potential: 22,
  },
  stage_transitions: {
    preclinical_to_ind: 0.90,
    phase_i_to_ii: 0.60,
    phase_ii_to_iii: 0.25,
    phase_iii_to_approval: 0.08,
    model_version: "Model v0.1",
    calibration_note: "Calibrated against terminated / failed oncology programs.",
  },
  resistance_mechanisms: [
    {
      name: "Dose reductions preventing target coverage",
      impact: "High",
      is_predicted: false,
      description: "Excessive wild-type EGFR-driven toxicities necessitate frequent dose reductions below target inhibition threshold.",
      evidence_ids: ["ev-poz-001"],
    },
  ],
  combinations: [],
  safety_profile: {
    common_aes: "Grade 3+ rash (>30%), Grade 3+ diarrhea (>25%), mucositis",
    dose_limiting_toxicities: "Severe dermatitis, diarrhea, dehydration",
    therapeutic_index: "Severely compromised / Unacceptable",
    discontinuation_rate: "High (>20% discontinuations, >70% dose reductions)",
    cardiac_risk: "Moderate",
    gi_toxicity_grade: "High",
    safety_score: 15,
  },
  patient_match: {
    best_patient_population: ["HER2 exon 20 insertion advanced tumors"],
    biomarkers: ["HER2 exon 20 insertion"],
    setting: "Advanced / Refractory",
    prior_lines: "Pre-treated",
    cns_metastases_benefit: false,
  },
  business_profile: {
    current_owner: "Spectrum / Hanmi",
    patent_ip: "Expired or deprioritized",
    commercial_opportunity: "Minimal (superseded by mutant-selective TKIs)",
    competitive_assets: "Zongertinib, Bay 2927088",
    licensing_partnering_feasibility: "Deprioritized; not recommended for partnering.",
    fto_legal_disclaimer: "IP and licensing information is derived from public patent registries and corporate disclosures.",
  },
  recommendation: {
    action: "AVOID",
    badge_text: "High Toxicity Liability - AVOID",
    rationale: "Unfavorable therapeutic index and severe wild-type EGFR toxicities resulted in FDA Complete Response Letter and negative ODAC vote.",
    confidence: 0.96,
    development_potential_score: 18,
    development_potential_tier: "Very Low",
  },
  supporting_evidence: [],
  contradicting_evidence: [
    {
      id: "ev-poz-001",
      source_type: "regulatory_authority",
      source_ref: "FDA:ODAC-2022-POZ",
      title: "FDA Oncologic Drugs Advisory Committee (ODAC) Briefing Document: Poziotinib",
      citation: "FDA ODAC Meeting September 22, 2022",
      publication_year: 2022,
      url: "https://www.fda.gov/advisory-committees/oncologic-drugs-advisory-committee",
      excerpt: "ODAC voted 9-4 that the benefits of poziotinib do not outweigh its risks in previously treated patients with HER2 exon 20 insertion NSCLC due to high toxicity and marginal durability.",
      polarity: "CONTRADICTING",
      is_verified: true,
      as_of_date: "2022-09-22",
    },
  ],
  unknowns: [],
  ai_inferences: [],
  last_updated: "2026-10-01",
};

export const ALL_ASSETS: AssetIntelligence[] = [
  ZONGERTINIB,
  NERATINIB,
  TUCATINIB,
  POZIOTINIB,
];

export function getAssetById(id: string): AssetIntelligence | undefined {
  return ALL_ASSETS.find((a) => a.id.toLowerCase() === id.toLowerCase());
}
